const family_data = [
    {
        id: 1,
        "Name ( नाम )": "Shivtahal ( शिवटहल )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '4',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 2,
        pid: 1,
        "Name ( नाम )": "Gya ( गया )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "Shivtahal ( शिवटहल )",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '1',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 3,
        pid: 1,
        "Name ( नाम )": "Badaree ( बदरी )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '4',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 4,
        pid: 1,
        "Name ( नाम )": "Kedar ( केदार )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '4',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 5,
        pid: 1,
        "Name ( नाम )": "Rameshar ( रामेशर )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 6,
        pid: 2,
        "Name ( नाम )": "Nakachedh ( नकछेद )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '3',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 7,
        pid: 6,
        "Name ( नाम )": "Ramashrey ( रामाश्रय )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 8,
        pid: 6,
        "Name ( नाम )": "Rampyare ( रामप्यारे )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '7',
        "No. Of Daughter ( पुत्री की संख्या )": '2',
        "Description ( विवरण )": "---",
    },
    {
        id: 9,
        pid: 6,
        "Name ( नाम )": "Triveni ( त्रिवेनी )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '3',
        "No. Of Daughter ( पुत्री की संख्या )": '---',
        "Description ( विवरण )": "---",
    },
    {
        id: 10,
        pid: 7,
        "Name ( नाम )": "Somai ( सोमई )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '---',
        "Description ( विवरण )": "---",
    },
    {
        id: 11,
        pid: 7,
        "Name ( नाम )": "Buddhu ( बुद्धू )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 12,
        pid: 9,
        "Name ( नाम )": "Sitlu ( सितलू )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '4',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 13,
        pid: 9,
        "Name ( नाम )": "Prem ( प्रेम )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '3',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 14,
        pid: 8,
        "Name ( नाम )": "Shree Bhagawat ( श्री भागवत )",
        "DOB ( जन्म की तारीख )": "1930 - 2014",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Humela ( हुमेला )",
        "Qualification ( योग्यता / शिक्षा )": "Class 8 ( कक्षा 8 )",
        "Occupation ( पेशा )": 'Soldier ( सैनिक )',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '2',
        "Description ( विवरण )": "---",
    },
    {
        id: 15,
        pid: 8,
        "Name ( नाम )": "Mahabeer ( महाबीर )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Manna ( मन्ना )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '3',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 16,
        pid: 8,
        "Name ( नाम )": "Raghuveer ( रघुवीर )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Runa ( रूना )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '0',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 17,
        pid: 8,
        "Name ( नाम )": "Ram Samuj ( राम समुझ )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Foolmati ( फूलमती )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Farmer ( किसान )',
        "No. Of Son ( पुत्र की संख्या )": '1',
        "No. Of Daughter ( पुत्री की संख्या )": '2',
        "Description ( विवरण )": "---",
    },
    {
        id: 18,
        pid: 8,
        "Name ( नाम )": "Ram Achal ( राम अचल )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Foolmati ( फूलमती )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Fci Karamchari ( एफसीआई कर्मचारी )',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 19,
        pid: 8,
        "Name ( नाम )": "Ram Naval ( राम नवल )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Tara ( तारा )",
        "Qualification ( योग्यता / शिक्षा )": "Graduation ( स्नातक )",
        "Occupation ( पेशा )": 'Store Keeper ( स्टोर कीपर )',
        "No. Of Son ( पुत्र की संख्या )": '4',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 20,
        pid: 8,
        "Name ( नाम )": "Ram Kaval ( राम कवल )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Store Keeper ( स्टोर कीपर )',
        "No. Of Son ( पुत्र की संख्या )": '3',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 21,
        pid: 8,
        "Name ( नाम )": "Kailashi ( कैलाशी )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Ganpat ( गणपत )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '2',
        "Description ( विवरण )": "---",
    },
    {
        id: 22,
        pid: 8,
        "Name ( नाम )": "Prabhavati ( प्रभावती )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '0',
        "No. Of Daughter ( पुत्री की संख्या )": '4',
        "Description ( विवरण )": "---",
    },
    {
        id: 23,
        pid: 14,
        "Name ( नाम )": "Shyam Karan ( श्याम करन )",
        "DOB ( जन्म की तारीख )": "1972",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "Jokhu ( जोखू )",
        "Wife/Husband ( पत्नी / पति )": "Suman ( सुमन )",
        "Qualification ( योग्यता / शिक्षा )": "High School ( हाई स्कूल )",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 24,
        pid: 14,
        "Name ( नाम )": "Ram Karan ( राम करन )",
        "DOB ( जन्म की तारीख )": "April 1975",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "Raju ( राजू )",
        "Wife/Husband ( पत्नी / पति )": "Rajeshwari ( राजेश्वरी )",
        "Qualification ( योग्यता / शिक्षा )": "High School ( हाई स्कूल )",
        "Occupation ( पेशा )": 'Auto mobile sales man ( ऑटोमोबाइल विक्रेता )',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 25,
        pid: 14,
        "Name ( नाम )": "Tarmati ( तारामती )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Shivdash ( शिवदाश )",
        "Qualification ( योग्यता / शिक्षा )": "High School ( हाई स्कूल )",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '3',
        "No. Of Daughter ( पुत्री की संख्या )": '3',
        "Description ( विवरण )": "---",
    },
    {
        id: 26,
        pid: 14,
        "Name ( नाम )": "Gayatri ( गायत्री )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '0',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 27,
        pid: 15,
        "Name ( नाम )": "Subansh ( सुबंश )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "Somnath ( सोमनाथ )",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '1',
        "No. Of Daughter ( पुत्री की संख्या )": '4',
        "Description ( विवरण )": "---",
    },
    {
        id: 28,
        pid: 15,
        "Name ( नाम )": "Lallan ( लल्लन )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "Somnath ( सोमनाथ )",
        "Wife/Husband ( पत्नी / पति )": "Arti ( आरती )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '2',
        "Description ( विवरण )": "---",
    },
    {
        id: 29,
        pid: 15,
        "Name ( नाम )": "Lalji ( लालजी )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Bijlawati ( बिजलावती )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '3',
        "Description ( विवरण )": "---",
    },
    {
        id: 30,
        pid: 15,
        "Name ( नाम )": "Lalti ( लालती )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Satram ( सतराम )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 31,
        pid: 16,
        "Name ( नाम )": "Baijanti ( बैजंती )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Avdhesh ( अवधेश )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '3',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 32,
        pid: 17,
        "Name ( नाम )": "Krishna mohan ( कृष्ण मोहन )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Reeta ( रीता )",
        "Qualification ( योग्यता / शिक्षा )": "B.A Graduate ( बी.ए स्नातक )",
        "Occupation ( पेशा )": 'Teacher ( अध्यापक )',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 33,
        pid: 17,
        "Name ( नाम )": "Sarmeela ( सरमीला )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 34,
        pid: 17,
        "Name ( नाम )": "Rinku ( रिंकू )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Chandrabhan ( चंद्रभान )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 35,
        pid: 18,
        "Name ( नाम )": "Shyam Mohan ( श्याम मोहन )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Sashi Kala ( शशि कला )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 36,
        pid: 18,
        "Name ( नाम )": "Madan ( मदन )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Sakuntala ( शकुंतला ) ( PHd Prefessor )",
        "Qualification ( योग्यता / शिक्षा )": "MSC Physics ( एमएससी भौतिकी )",
        "Occupation ( पेशा )": 'Samikha Adhikari ( समीक्षा अधिकारी )',
        "No. Of Son ( पुत्र की संख्या )": '1',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 37,
        pid: 18,
        "Name ( नाम )": "Anita ( अनीता )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Amarjeet ( अमरजीत )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '0',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 38,
        pid: 19,
        "Name ( नाम )": "Sanjay ( संजय )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "Maina ( मैना ) ( Teacher )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Doctor ( private practice ) डॉक्टर (निजी प्रैक्टिस)',
        "No. Of Son ( पुत्र की संख्या )": '1',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 39,
        pid: 19,
        "Name ( नाम )": "Ajay ( अजय )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "Guddu ( गुड्डू )",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "Graduation ( स्नातक )",
        "Occupation ( पेशा )": 'Sub inspector in cisf ( सीआईएसएफ में सब इंस्पेक्टर )',
        "No. Of Son ( पुत्र की संख्या )": '1',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 40,
        pid: 19,
        "Name ( नाम )": "Krishna Gopal ( कृष्ण गोपाल )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "Tinku ( टिंकू )",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Soldier ( सैनिक )',
        "No. Of Son ( पुत्र की संख्या )": '0',
        "No. Of Daughter ( पुत्री की संख्या )": '2',
        "Description ( विवरण )": "---",
    },
    {
        id: 41,
        pid: 19,
        "Name ( नाम )": "Praveen ( प्रवीण )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "Mantu ( मंटू )",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "Engineering ( अभियांत्रिकी )",
        "Occupation ( पेशा )": 'Private job ( प्राइवेट नौकरी )',
        "No. Of Son ( पुत्र की संख्या )": '0',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 42,
        pid: 19,
        "Name ( नाम )": "Suneeta ( सुनीता )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "Mantu ( मंटू )",
        "Wife/Husband ( पत्नी / पति )": "Shivanand ( शिवानंद )",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '1',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 43,
        pid: 20,
        "Name ( नाम )": "Manoj ( मनोज )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "Bablu ( बबलू )",
        "Wife/Husband ( पत्नी / पति )": "Sarooj ( सरोज )",
        "Qualification ( योग्यता / शिक्षा )": "Class 8 ( कक्षा 8 )",
        "Occupation ( पेशा )": 'Shop ( दुकान )',
        "No. Of Son ( पुत्र की संख्या )": '2',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 44,
        pid: 20,
        "Name ( नाम )": "Anil ( अनिल )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "Pintu ( पिंटू )",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '1',
        "No. Of Daughter ( पुत्री की संख्या )": '1',
        "Description ( विवरण )": "---",
    },
    {
        id: 45,
        pid: 20,
        "Name ( नाम )": "Dileep ( दिलीप )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "---",
        Picture: "https://cdn.balkan.app/shared/empty-img-blue.svg",
        "Other Name ( अन्य नाम )": "---",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '0',
        "No. Of Daughter ( पुत्री की संख्या )": '2',
        "Description ( विवरण )": "---",
    },
    {
        id: 47,
        pid: 23,
        "Name ( नाम )": "Kuldeep ( कुलदीप )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "Shyam Karan ( श्याम करन )",
        Picture: "images/kuldeep_giri.jpg",
        "Other Name ( अन्य नाम )": "Neeraj ( नीरज )",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": 'Teacher ( अध्यापक )',
        "No. Of Son ( पुत्र की संख्या )": '0',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 48,
        pid: 23,
        "Name ( नाम )": "Avinash ( अविनाश )",
        "DOB ( जन्म की तारीख )": "---",
        "SO/DO ( पुत्र / पुत्री )": "Shyam Karan ( श्याम करन )",
        Picture: "images/avinash_giri.jpg",
        "Other Name ( अन्य नाम )": "Golu ( गोलू )",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "---",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '0',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 49,
        pid: 24,
        "Name ( नाम )": "Shashank ( शशांक )",
        "DOB ( जन्म की तारीख )": "20-05-1998",
        "SO/DO ( पुत्र / पुत्री )": "Ram Karan ( राम करन )",
        Picture: "images/shashank_goswami.jpg",
        "Other Name ( अन्य नाम )": "Suraj ( सूरज )",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "Law ( कानून )",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '0',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 50,
        pid: 24,
        "Name ( नाम )": "Vaibhav ( वैभव )",
        "DOB ( जन्म की तारीख )": "23-03-2000",
        "SO/DO ( पुत्र / पुत्री )": "Ram Karan ( राम करन )",
        Picture: "images/vaibhav_goswami.jpg",
        "Other Name ( अन्य नाम )": "Bholu ( भोलू )",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "B.Tech Computer Science Engineering ( बीटेक कंप्यूटर साइंस इंजीनियरिंग )",
        "Occupation ( पेशा )": 'Software Engineer',
        "No. Of Son ( पुत्र की संख्या )": '0',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },
    {
        id: 51,
        pid: 24,
        "Name ( नाम )": "Sneha ( स्नेहा )",
        "DOB ( जन्म की तारीख )": "12-01-1996",
        "SO/DO ( पुत्र / पुत्री )": "Ram Karan ( राम करन )",
        Picture: "images/sneha_goswami.jpg",
        "Other Name ( अन्य नाम )": "Anamika ( अनामिका )",
        "Wife/Husband ( पत्नी / पति )": "---",
        "Qualification ( योग्यता / शिक्षा )": "M.B.A ( एम.बी.ए )",
        "Occupation ( पेशा )": '---',
        "No. Of Son ( पुत्र की संख्या )": '0',
        "No. Of Daughter ( पुत्री की संख्या )": '0',
        "Description ( विवरण )": "---",
    },

]